[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
identity_iota = { git = "https://github.com/iotaledger/identity.rs", tag = "v1.6.0-beta"}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.5", features = ["fs"]}

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"