[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
axum-extra = { version = "0.9", features = ["cookie"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
identity_iota = { git = "https://github.com/iotaledger/identity.rs", tag = "v1.6.0-beta"}
iota-sdk = { version = "1.0", default-features = false, features = ["client", "tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "2"
tower-http = { version = "0.5", features = ["fs"]}
rust-ipfs = "0.14.1"
reduct-rs = "1"
futures = "0.3"
futures-util = "0.3"
envie = "0.2.1"
lazy-regex = "2"
async-trait = "0.1"
tower-cookies = "0.11.0"
strum_macros = "0.24"
uuid = {version = "1", features = ["v4", "fast-rng"]}
chrono = "0.4"
sha2 = "0.10"
hex = "0.4"
ed25519-dalek = "2.0"
base64 = "0.21"
rand = "0.8"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
