[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
axum-extra = { version = "0.9", features = ["cookie"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
identity_iota = { git = "https://github.com/iotaledger/identity.rs", tag = "v1.6.0-beta"}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower-http = { version = "0.5", features = ["fs"]}
uuid = "1.18.1"
rust-ipfs = "0.14.1"
reduct-rs = "1"
futures = "0.3"
futures-util = "0.3"
envie = "0.2.1"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
